name: Build and Push to ECR

on:
  push:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: codesavvysm/clo835_winter2025_assignment1
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Webapp Image
        run: |
          docker build -t webapp .
          docker tag webapp:latest ${{ steps.login-ecr.outputs.registry }}/webapp:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/webapp:latest

      - name: Build MySQL Image
        run: |
          docker build -t mysql -f mysql/Dockerfile ./mysql
          docker tag mysql:latest ${{ steps.login-ecr.outputs.registry }}/mysql:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/mysql:latest
